khoait/DCE.PCF

- PolyLookupComponent/.eslintrc.json
- PolyLookupComponent/.gitignore
- PolyLookupComponent/PolyLookup/ControlManifest.Input.xml
- PolyLookupComponent/PolyLookup/components/PolyLookupControl.tsx
- PolyLookupComponent/PolyLookup/index.ts
- PolyLookupComponent/PolyLookup/services/DataverseService.ts
- PolyLookupComponent/PolyLookupComponent.pcfproj
- PolyLookupComponent/package-lock.json
- PolyLookupComponent/package.json
- PolyLookupComponent/pcfconfig.json
- PolyLookupComponent/selected.json
- PolyLookupComponent/suggestions.json
- PolyLookupComponent/tsconfig.json
- README.md
- solution/.gitignore
- solution/solution.cdsproj
- solution/src/Other/Customizations.xml
- solution/src/Other/Relationships.xml
- solution/src/Other/Solution.xml
Added first component PolyLookup
> PolyLookup initial

- PolyLookupComponent/PolyLookup/ControlManifest.Input.xml
- PolyLookupComponent/PolyLookup/components/PolyLookupControl.tsx
- PolyLookupComponent/PolyLookup/index.ts
- PolyLookupComponent/PolyLookup/services/DataverseService.ts
- PolyLookupComponent/package-lock.json
- PolyLookupComponent/package.json
- Use Odata Web API to search
- Search by Primary Name attribute only
- Data is sorted using Sort By prop
- Added Lookup View prop and removed Sort By prop
- Use FetchXml from the View definition to filter data
- Search on multiple columns with dynamic templating
- Search by dependent data on the current record with dynamic templating
- Limit search results to only first page for now (will be addressed in #8)
Completed #6
> Dynamic search filter

- PolyLookupComponent/PolyLookup/components/PolyLookupControl.tsx
- PolyLookupComponent/PolyLookup/services/DataverseService.ts
- special type column displays raw data in suggestion item.
- use formatted value.
- #7
> fixed display value and tag data

- PolyLookupComponent/PolyLookup/ControlManifest.Input.xml
- PolyLookupComponent/PolyLookup/components/PolyLookupControl.tsx
- PolyLookupComponent/PolyLookup/components/SuggestionInfo.tsx
- PolyLookupComponent/PolyLookup/index.ts
- Selected texts are output as text to the bound field
- Selected items are output as JSON array to an additional field optionally
- completed #19
> output selected items as JSON array

- PolyLookupComponent/PolyLookup/components/PolyLookupControl.tsx
- PolyLookupComponent/PolyLookup/index.ts
- PolyLookupComponent/PolyLookup/types/handlebars.ts
- build failed with handlebars import
- black border color
- getClientUrl error in test harness
- workaround handlebars import
- updated border color to match OOTB controls
- fixed getClientUrl in test harness.
- fixed #17
> Fixed handlebars import build error

- PolyLookupComponent/PolyLookup/ControlManifest.Input.xml
- PolyLookupComponent/PolyLookup/components/PolyLookupControl.tsx
- solution/src/Other/Solution.xml
- Suggestion list only shows the first page when filtering.
- Load more button to load the second page.
- completed #8
> added load more button

- PolyLookupComponent/PolyLookup/ControlManifest.Input.xml
- PolyLookupComponent/PolyLookup/components/PolyLookupControl.tsx
- PolyLookupComponent/PolyLookup/index.ts
- PolyLookupComponent/PolyLookup/services/DataverseService.ts
- solution/src/Other/Solution.xml
- json output not working correctly in create form
- fixed json output by checking form type and use a separate state
- updated placeholder message
- allow field binding to singleline text, text area, multiple lines text fields
- fixed #29
> fixed json output in create form

- LookdownComponent/Lookdown/components/LookdownControl.tsx
- LookdownComponent/Lookdown/index.ts
- LookdownComponent/Lookdown/services/DataverseService.ts
- LookdownComponent/Lookdown/types/metadata.ts
- shows sample data
- loads selected lookup value
- loads option data from lookup view
- #56
> load data using view and output selected item.

- LookdownComponent/Lookdown/ControlManifest.Input.xml
- LookdownComponent/Lookdown/components/LookdownControl.tsx
- LookdownComponent/Lookdown/index.ts
- LookdownComponent/Lookdown/services/DataverseService.ts
- no grouping
- group by a column in lookup view, automcatically queried if not included in lookup view
- #58
> 58-grouping

- LookdownComponent/Lookdown/ControlManifest.Input.xml
- LookdownComponent/Lookdown/components/LookdownControl.tsx
- LookdownComponent/Lookdown/index.ts
- LookdownComponent/Lookdown/services/DataverseService.ts
- LookdownComponent/Lookdown/types/metadata.ts
- LookdownComponent/package-lock.json
- LookdownComponent/package.json
- option with no icon
- optionally show icon with sizes
- #59
> added show icon prop and option with image layout

- LookdownComponent/.eslintrc.json
- LookdownComponent/.gitignore
- LookdownComponent/.prettierrc.json
- LookdownComponent/.vscode/settings.json
- LookdownComponent/Lookdown/ControlManifest.Input.xml
- LookdownComponent/Lookdown/components/LookdownControl.tsx
- LookdownComponent/Lookdown/index.ts
- LookdownComponent/Lookdown/services/DataverseService.ts
- LookdownComponent/Lookdown/types/metadata.ts
- LookdownComponent/LookdownComponent.pcfproj
- LookdownComponent/package-lock.json
- LookdownComponent/package.json
- LookdownComponent/pcfconfig.json
- LookdownComponent/tsconfig.json
- added Lookdown component
- #55
> added Lookdown component

- LookdownComponent/Lookdown/ControlManifest.Input.xml
- LookdownComponent/Lookdown/components/LookdownControl.tsx
- LookdownComponent/Lookdown/index.ts
- LookdownComponent/Lookdown/services/DataverseService.ts
- PolyLookupComponent/PolyLookup/ControlManifest.Input.xml
- PolyLookupComponent/PolyLookup/components/PolyLookupControl.tsx
- PolyLookupComponent/package-lock.json
- PolyLookupComponent/package.json
- solution/solution.cdsproj
- solution/src/Other/Solution.xml
- no dynamic filter for Lookdown
- dynamic filter can be applied using lookup view or custom filter prop
- fixed handlebars version in PolyLookup
- #61 
- #17
> added dynamic filter to Lookdown

- PolyLookupComponent/.vscode/settings.json
- PolyLookupComponent/PolyLookup/ControlManifest.Input.xml
- PolyLookupComponent/PolyLookup/components/PolyLookupControl.tsx
- PolyLookupComponent/PolyLookup/index.ts
- PolyLookupComponent/PolyLookup/services/DataverseService.ts
- PolyLookupComponent/PolyLookup/types/metadata.ts
- Connection relationship was not supported
- Connection relationship should work similar to Custom N:N
- #77
> added Connection relationship

- LookdownComponent/Lookdown/ControlManifest.Input.xml
- LookdownComponent/Lookdown/components/LookdownControl.tsx
- LookdownComponent/Lookdown/index.ts
- LookdownComponent/Lookdown/services/DataverseService.ts
- LookdownComponent/tsconfig.json
- PolyLookupComponent/PolyLookup/ControlManifest.Input.xml
- only display option and selected option text using primary attribute
- option and selected option text can be customized using dynamic template
- closes #62 
- closes #63
> added option template

- LookdownComponent/Lookdown/ControlManifest.Input.xml
- LookdownComponent/Lookdown/components/LookdownControl.tsx
- LookdownComponent/Lookdown/index.ts
- LookdownComponent/Lookdown/services/DataverseService.ts
- no commands
- commands to open selected record, quick create, and lookup panel
- closes #64 
- closes #65
> added commands

- LookdownComponent/.eslintrc.json
- LookdownComponent/package-lock.json
- LookdownComponent/package.json
- PolyLookupComponent/.eslintrc.json
- PolyLookupComponent/PolyLookup/services/DataverseService.ts
- solution/src/Other/Solution.xml
- selected values are not loaded in inactive form
- selected values should be loaded correctly in inactive form
- #88
> fixed selected values in inactive form

- LookdownComponent/package-lock.json
- PolyLookupComponent/package-lock.json
Upgrade dependencies from dependabot
> Upgrade dependencies

- LookdownComponent/.vscode/settings.json
- LookdownComponent/Lookdown/ControlManifest.Input.xml
- LookdownComponent/Lookdown/components/LookdownControl.tsx
- LookdownComponent/Lookdown/index.ts
- LookdownComponent/Lookdown/services/DataverseService.ts
- LookdownComponent/Lookdown/strings/Lookdown.1033.resx
- LookdownComponent/Lookdown/types/languagePack.ts
- PolyLookupComponent/PolyLookup/ControlManifest.Input.xml
- PolyLookupComponent/PolyLookup/components/PolyLookupControl.tsx
- PolyLookupComponent/PolyLookup/index.ts
- PolyLookupComponent/PolyLookup/services/DataverseService.ts
- PolyLookupComponent/PolyLookup/strings/PolyLookup.1033.resx
- PolyLookupComponent/PolyLookup/types/languagePack.ts
- PolyLookupComponent/package-lock.json
- PolyLookupComponent/package.json
- README.md
- solution/src/Other/Solution.xml
- English default.
- A language pack can be used to override the default language.
- #95
> added language pack support

- TimePickerComponent/.eslintrc.json
- TimePickerComponent/.gitignore
- TimePickerComponent/TimePicker/ControlManifest.Input.xml
- TimePickerComponent/TimePicker/components/TimePickerControl.tsx
- TimePickerComponent/TimePicker/components/TimePickerControlNewLook.tsx
- TimePickerComponent/TimePicker/index.ts
- TimePickerComponent/TimePicker/services/dateService.ts
- TimePickerComponent/TimePicker/types/extendedContext.ts
- TimePickerComponent/TimePicker/types/typings.ts
- TimePickerComponent/TimePickerComponent.pcfproj
- TimePickerComponent/package-lock.json
- TimePickerComponent/package.json
- TimePickerComponent/pcfconfig.json
- TimePickerComponent/tsconfig.json
> added Timepicker component

- TimePickerComponent/TimePicker/components/TimePickerControl.tsx
- TimePickerComponent/TimePicker/components/TimePickerControlNewLook.tsx
- chevron down icon
- time icon
- #102
> TimePicker use time icon

- PolyLookupComponent/PolyLookup/ControlManifest.Input.xml
- PolyLookupComponent/PolyLookup/components/PolyLookupControl.tsx
- PolyLookupComponent/PolyLookup/index.ts
- underscore (`_`) in column logical name is treated as a wildcard and repaced with `[_]` in `like` operator causing column variables are not populated.
- unnecessary re-renders when trying to update output in first load.
- fixed wildcard escaping in variable placeholder.
- fixed rerender.
- fixed #117
> fixed wildcard escaping in variable placeholder.

- PolyLookupComponent/.eslintrc.json
- PolyLookupComponent/PolyLookup/ControlManifest.Input.xml
- PolyLookupComponent/PolyLookup/components/PolyLookupControl.tsx
- PolyLookupComponent/PolyLookup/index.ts
- PolyLookupComponent/PolyLookup/services/DataverseService.ts
- PolyLookupComponent/PolyLookup/strings/PolyLookup.1033.resx
- PolyLookupComponent/PolyLookup/types/languagePack.ts
- PolyLookupComponent/PolyLookup/types/metadata.ts
- PolyLookupComponent/package-lock.json
- PolyLookupComponent/package.json
- Lookup View only uses FetchXML from a system view.
- FetchXML can be passed dynamically using:
- static fetch or bind to a form field
- odata url
- environment variable
- system view name
- completed #121
> added lookup view configuration

- LookdownComponent/Lookdown/components/LookdownControlNewLook.tsx
fixed extracting dynamic variables
> fixed fetchxml input

- PolyLookupComponent/PolyLookup/components/PolyLookupControlClassic.tsx
- PolyLookupComponent/PolyLookup/components/PolyLookupControlNewLook.tsx
- PolyLookupComponent/PolyLookup/services/DataverseService.ts
- use small size
- added underline to clickable selected item
- removed selected item from options
- fixed #138
> added minor enhancements

- LookdownComponent/Lookdown/components/LookdownControlClassic.tsx
- LookdownComponent/package-lock.json
- solution/src/Other/Solution.xml
- all controls now support new look
- completed #84
> completed new look

- PolyLookupComponent/PolyLookup/ControlManifest.Input.xml
- PolyLookupComponent/PolyLookup/components/PolyLookupControlNewLook.tsx
- no constrain on the popover size. the popover height will be calculated automatically but this has an issue in the modern form.
- set max height to 50vh (half screen height) looks good
- fixed #160
> fixed popover height

- PolyLookupComponent/PolyLookup/components/PolyLookupControlNewLook.tsx
- PolyLookupComponent/PolyLookup/services/DataverseService.ts
- loading message always shows in create form
- fixed message and selection behavior in create form
- fixed #162
> fixed selected options in create form

- LookdownComponent/Lookdown/ControlManifest.Input.xml
- LookdownComponent/Lookdown/services/DataverseService.ts
- PolyLookupComponent/PolyLookup/ControlManifest.Input.xml
- PolyLookupComponent/PolyLookup/components/SuggestionInfo.tsx
- PolyLookupComponent/PolyLookup/services/DataverseService.ts
- lookup field value doesn't display
- lookup field value should display using formatted value
- fixed #177
> fixed getting formatted values

- PolyLookupComponent/PolyLookup/components/PolyLookupControlClassic.tsx
- PolyLookupComponent/PolyLookup/components/PolyLookupControlNewLook.tsx
- PolyLookupComponent/PolyLookup/services/DataverseService.ts
- fixed selected items font size
- fixed icon background
- clear search text after selection
- more records available indicator
- fixed #171
> added enhancements in new look

- PolyLookupComponent/PolyLookup/components/PolyLookupControlNewLook.tsx
- PolyLookupComponent/PolyLookup/services/DataverseService.ts
- fixed newly quick created item not associated by removing curly braces from id values
- fixed #183
> fixed newly quick created item not associated

- LookdownComponent/Lookdown/components/LookdownControlClassic.tsx
- LookdownComponent/Lookdown/components/LookdownControlNewLook.tsx
- updated LookDown disabled styles in new look
- fixed #190
> updated lookdown disabled styles
